name: deploy-to-s3
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - master

jobs:
  bucket-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        id: step1
        uses: actions/checkout@v4

      - name: Setup AWS credentials
        id: step2
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::816698261168:role/trinity-tech-solutions.com
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to S3
        id: step3
        run: aws s3 sync . s3://trinity-tech-solutions.com --delete
